#!/usr/bin/python


import optparse

def parse_args():
    p = optparse.OptionParser()
    p.add_option("-D", "--driver", dest="driver", help="Database driver")
    p.add_option("-h", "--host", dest="host", help="Host name for the database connection")
    p.add_option("-d", "--database", dest="database", help="database name")
    p.add_option("-u", "--user", dest="user", help="database user")
    p.add_option("-p", "--password", dest="password", help="database password")
    p.add_option("-o", "--output", dest="outfile", help="output file name")
    p.add_option("-t", "--type", dest="outtype", help="output file type")
    (options, args) = p.parse_args()
    #TODO: verify options, import classes
    return options
